ALTER TYPE "application_status" ADD VALUE IF NOT EXISTS 'APPLICATION_STUDENT_ACTION_REQUIRED' AFTER 'APPLICATION_SUBMISSION';
ALTER TYPE "application_status" ADD VALUE IF NOT EXISTS 'APPLICATION_REJECTED_BY_UNIVERSITY' AFTER 'APPLICATION_STUDENT_ACTION_REQUIRED';
