'use client'

import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { Check, Crown, LogOut, Save, ShieldCheck } from 'lucide-react'
import { getStudentSupport } from '@/features/support/support.functions'
import type { Account } from '@/lib/store'
import { cn } from '@/lib/utils'
import type { OnboardingData, StudentAgencyDetails } from '@/types'
import { Panel, fadeUp } from './bits'

interface Props {profile:OnboardingData|null;account:Account|null;onSaveAccount:(account:Account)=>Promise<unknown>;onSaveAgencyProfile:(details:StudentAgencyDetails)=>Promise<unknown>;onSignOut:()=>void}
type SettingsTab='profile'|'academics'|'subscription'|'account'
const inputCls='w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-[13px] outline-none transition placeholder:text-white/30 focus:border-amber-400/60'
const selectCls=cn(inputCls,'cursor-pointer [&>option]:bg-[#0a0f24]')
const emptyDetails:StudentAgencyDetails={dateOfBirth:'',gender:'',maritalStatus:'',nationality:'',residenceCountry:'',addressLine:'',city:'',state:'',postalCode:'',passportStatus:'',passportNumber:'',passportExpiry:'',preferredContactMethod:'',whatsappNumber:'',emergencyContactName:'',emergencyContactRelation:'',emergencyContactPhone:'',fundingSource:'',sponsorName:'',educationLoanStatus:'',visaRefusalHistory:'NO',visaRefusalDetails:'',travelHistory:'',workExperienceYears:'',counsellingNotes:''}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.13em] text-white/40">{label}</span>{children}</label>}
function ReadOnly({label,value}:{label:string;value?:string|number|null}){return <div className="rounded-xl border border-white/[.07] bg-white/[.025] p-4"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-white/30">{label}</p><p className="mt-1.5 text-xs text-white/75">{value||'Not provided'}</p></div>}
function Section({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <Panel className="p-5 sm:p-6"><p className="text-[11px] font-semibold uppercase tracking-[.2em] text-white/45">{title}</p><p className="mt-1 text-xs text-white/35">{description}</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{children}</div></Panel>}

export default function Settings({profile,account,onSaveAccount,onSaveAgencyProfile,onSignOut}:Props){
  const [tab,setTab]=useState<SettingsTab>('profile'),[name,setName]=useState(account?.name??''),[email,setEmail]=useState(account?.email??''),[phone,setPhone]=useState(account?.phone??''),[details,setDetails]=useState<StudentAgencyDetails>({...emptyDetails,...profile?.agencyDetails}),[saving,setSaving]=useState(false),[message,setMessage]=useState<{type:'success'|'error';text:string}|null>(null),[subscription,setSubscription]=useState<any>()
  useEffect(()=>{setName(account?.name??'');setEmail(account?.email??'');setPhone(account?.phone??'')},[account])
  useEffect(()=>setDetails({...emptyDetails,...profile?.agencyDetails}),[profile])
  useEffect(()=>{getStudentSupport().then(setSubscription)},[])
  const patch=(changes:Partial<StudentAgencyDetails>)=>setDetails(current=>({...current,...changes}))
  const save=async()=>{try{setSaving(true);setMessage(null);await Promise.all([onSaveAccount({name:name.trim(),email:email.trim(),phone:phone.trim()}),onSaveAgencyProfile(details)]);setMessage({type:'success',text:'Your profile has been updated.'})}catch(error){setMessage({type:'error',text:error instanceof Error?error.message:'Unable to save your profile.'})}finally{setSaving(false)}}
  const saveBar=<>{message&&<p className={cn('text-xs',message.type==='success'?'text-emerald-300':'text-rose-300')}>{message.text}</p>}<button disabled={saving||!profile} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-amber-300 to-amber-500 px-6 py-3.5 text-[13px] font-semibold text-[#0a0f24] disabled:opacity-50">{message?.type==='success'?<Check className="size-4"/>:<Save className="size-4"/>}{saving?'Saving…':'Save profile'}</button></>
  return <div className="max-w-4xl space-y-5">
    <motion.div variants={fadeUp} initial="hidden" animate="show"><div className="flex gap-1 overflow-x-auto rounded-2xl border border-white/10 bg-white/[.025] p-1.5">{([{id:'profile',label:'Profile'},{id:'academics',label:'Academics'},{id:'subscription',label:'Subscription'},{id:'account',label:'Account'}] as const).map(item=><button key={item.id} onClick={()=>setTab(item.id)} className={cn('rounded-xl px-4 py-2.5 text-xs font-semibold transition',tab===item.id?'bg-amber-400 text-[#0a0f24]':'text-white/45 hover:bg-white/[.05] hover:text-white')}>{item.label}</button>)}</div></motion.div>
    {tab==='profile'&&<>
      <Section title="Personal and contact details" description="Your legal and current contact information."><Field label="Full legal name"><input value={name} onChange={e=>setName(e.target.value)} className={inputCls}/></Field><Field label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className={inputCls}/></Field><Field label="Phone"><input value={phone} onChange={e=>setPhone(e.target.value)} className={inputCls}/></Field><Field label="WhatsApp number"><input value={details.whatsappNumber} onChange={e=>patch({whatsappNumber:e.target.value})} className={inputCls}/></Field><Field label="Date of birth"><input type="date" value={details.dateOfBirth} onChange={e=>patch({dateOfBirth:e.target.value})} className={inputCls}/></Field><Field label="Gender"><select value={details.gender} onChange={e=>patch({gender:e.target.value})} className={selectCls}><option value="">Select</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></Field><Field label="Marital status"><select value={details.maritalStatus} onChange={e=>patch({maritalStatus:e.target.value})} className={selectCls}><option value="">Select</option><option>Single</option><option>Married</option><option>Other</option></select></Field><Field label="Nationality"><input value={details.nationality} onChange={e=>patch({nationality:e.target.value})} className={inputCls}/></Field><Field label="Current country of residence"><input value={details.residenceCountry} onChange={e=>patch({residenceCountry:e.target.value})} className={inputCls}/></Field><Field label="Preferred contact"><select value={details.preferredContactMethod} onChange={e=>patch({preferredContactMethod:e.target.value})} className={selectCls}><option value="">Select</option><option>Email</option><option>Phone</option><option>WhatsApp</option></select></Field><Field label="Address"><textarea value={details.addressLine} onChange={e=>patch({addressLine:e.target.value})} rows={3} className={inputCls}/></Field><div className="grid grid-cols-2 gap-3"><Field label="City"><input value={details.city} onChange={e=>patch({city:e.target.value})} className={inputCls}/></Field><Field label="State"><input value={details.state} onChange={e=>patch({state:e.target.value})} className={inputCls}/></Field></div><Field label="Postal code"><input value={details.postalCode} onChange={e=>patch({postalCode:e.target.value})} className={inputCls}/></Field></Section>
      <Section title="Passport and travel" description="Required for admissions and visa planning."><Field label="Passport status"><select value={details.passportStatus} onChange={e=>patch({passportStatus:e.target.value})} className={selectCls}><option value="">Select</option><option>Available</option><option>Applied</option><option>Not applied</option></select></Field><Field label="Passport number"><input disabled={details.passportStatus!=='Available'} value={details.passportNumber} onChange={e=>patch({passportNumber:e.target.value})} className={inputCls}/></Field><Field label="Passport expiry"><input disabled={details.passportStatus!=='Available'} type="date" value={details.passportExpiry} onChange={e=>patch({passportExpiry:e.target.value})} className={inputCls}/></Field><Field label="Previous visa refusal"><select value={details.visaRefusalHistory} onChange={e=>patch({visaRefusalHistory:e.target.value})} className={selectCls}><option value="NO">No</option><option value="YES">Yes</option></select></Field>{details.visaRefusalHistory==='YES'&&<div className="sm:col-span-2"><Field label="Visa refusal details"><textarea value={details.visaRefusalDetails} onChange={e=>patch({visaRefusalDetails:e.target.value})} rows={3} className={inputCls}/></Field></div>}<div className="sm:col-span-2"><Field label="International travel history"><textarea value={details.travelHistory} onChange={e=>patch({travelHistory:e.target.value})} rows={3} placeholder="Countries visited, visa type and year" className={inputCls}/></Field></div></Section>
      <Section title="Funding and experience" description="Helps us plan affordability, scholarships and financial documents."><Field label="Primary funding source"><select value={details.fundingSource} onChange={e=>patch({fundingSource:e.target.value})} className={selectCls}><option value="">Select</option><option>Self-funded</option><option>Parents / family</option><option>Education loan</option><option>Scholarship</option><option>Employer / sponsor</option></select></Field><Field label="Sponsor name"><input value={details.sponsorName} onChange={e=>patch({sponsorName:e.target.value})} className={inputCls}/></Field><Field label="Education loan status"><select value={details.educationLoanStatus} onChange={e=>patch({educationLoanStatus:e.target.value})} className={selectCls}><option value="">Select</option><option>Not required</option><option>Planning to apply</option><option>In progress</option><option>Pre-approved</option><option>Approved</option></select></Field><Field label="Work experience (years)"><input type="number" min="0" max="50" value={details.workExperienceYears} onChange={e=>patch({workExperienceYears:e.target.value})} className={inputCls}/></Field><div className="sm:col-span-2"><Field label="Goals or counsellor notes"><textarea value={details.counsellingNotes} onChange={e=>patch({counsellingNotes:e.target.value})} rows={4} placeholder="Career goals, concerns, preferred cities, dependants or anything your counsellor should know" className={inputCls}/></Field></div></Section>
      <Section title="Emergency contact" description="A trusted family member or guardian."><Field label="Contact name"><input value={details.emergencyContactName} onChange={e=>patch({emergencyContactName:e.target.value})} className={inputCls}/></Field><Field label="Relationship"><input value={details.emergencyContactRelation} onChange={e=>patch({emergencyContactRelation:e.target.value})} className={inputCls}/></Field><Field label="Contact phone"><input value={details.emergencyContactPhone} onChange={e=>patch({emergencyContactPhone:e.target.value})} className={inputCls}/></Field></Section>
      <div className="flex flex-wrap items-center gap-4">{saveBar}</div>
    </>}
    {tab==='academics'&&<Panel className="p-5 sm:p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 text-amber-300"/><div><p className="text-sm font-semibold">Academic profile is locked</p><p className="mt-1 text-xs leading-5 text-white/40">These verified onboarding details cannot be edited by the student. Contact your counsellor if a correction is required.</p></div></div>{profile?<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><ReadOnly label="Destination" value={profile.country?.name}/><ReadOnly label="Education" value={profile.educationLevel}/><ReadOnly label="Degree" value={profile.degree}/><ReadOnly label="Courses" value={profile.fields?.join(', ')||profile.field}/><ReadOnly label="GPA" value={profile.gpa}/><ReadOnly label="Graduation year" value={profile.gradYear}/><ReadOnly label="English tests" value={profile.englishTest}/><ReadOnly label="Preferred intake" value={profile.intake.replace(':',' · ')}/><ReadOnly label="Annual tuition preference" value={`₹${((profile.feeMinInr??0)/100000).toFixed(0)}–${profile.feeMaxInr===100000000?'50+':((profile.feeMaxInr??0)/100000).toFixed(0)} lakh`}/></div>:<p className="mt-5 text-sm text-white/40">No onboarding profile found.</p>}</Panel>}
    {tab==='subscription'&&<Panel className="p-6"><div className="flex items-center gap-2"><Crown className="size-5 text-amber-300"/><h3 className="font-display text-2xl">Mygreat Pro</h3></div><p className="mt-3 text-sm text-white/45">{subscription?.subscription?.status==='ACTIVE'?'Your Pro membership is active.':'Manage your study-abroad support subscription.'}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><ReadOnly label="Plan" value={subscription?.plan?.displayPrice??'₹999 / month'}/><ReadOnly label="Status" value={subscription?.subscription?.status??'FREE'}/><ReadOnly label="Payment" value={subscription?.subscription?.method?.replaceAll('_',' ')}/></div></Panel>}
    {tab==='account'&&<Panel className="p-6"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-amber-300"/><h3 className="font-display text-2xl">Account security</h3></div><p className="mt-2 text-xs text-white/40">Sign out from this device securely.</p><button onClick={onSignOut} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-white/12 px-5 py-3 text-sm font-semibold text-white/70"><LogOut className="size-4"/>Sign out</button></Panel>}
  </div>
}
