/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R503RouteImport } from './routes/503'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as ApiSupportRouteImport } from './routes/api.support'
import { Route as ApiWorkflowRouteImport } from './routes/api.workflow'
import { Route as LoginAccountTypeRouteImport } from './routes/login.$accountType'
import { Route as PartnerRegisterRouteImport } from './routes/partner.register'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffApplicationsRouteImport } from './routes/staff.applications'
import { Route as StaffFinanceRouteImport } from './routes/staff.finance'
import { Route as StaffMessagesRouteImport } from './routes/staff.messages'
import { Route as StaffNotificationsRouteImport } from './routes/staff.notifications'
import { Route as StaffPartnersRouteImport } from './routes/staff.partners'
import { Route as StaffSettingsRouteImport } from './routes/staff.settings'
import { Route as StaffStudentsRouteImport } from './routes/staff.students'
import { Route as StaffTeamRouteImport } from './routes/staff.team'
import { Route as StaffUniversitiesRouteImport } from './routes/staff.universities'
import { Route as StaffVisasRouteImport } from './routes/staff.visas'
import { Route as ApiAuthAccountRouteImport } from './routes/api.auth.account'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiPartnersRegisterRouteImport } from './routes/api.partners.register'
import { Route as StaffApplicationsIndexRouteImport } from './routes/staff.applications.index'
import { Route as StaffApplicationsApplicationIdRouteImport } from './routes/staff.applications.$applicationId'
import { Route as StaffPartnersPartnerCompanyIdRouteImport } from './routes/staff.partners.$partnerCompanyId'
import { Route as StaffStudentsStudentIdRouteImport } from './routes/staff.students.$studentId'
import { Route as StaffVisasIndexRouteImport } from './routes/staff.visas.index'
import { Route as StaffVisasApplicationIdRouteImport } from './routes/staff.visas.$applicationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R503Route = R503RouteImport.update({
  id: '/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportRoute = ApiSupportRouteImport.update({
  id: '/api/support',
  path: '/api/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowRoute = ApiWorkflowRouteImport.update({
  id: '/api/workflow',
  path: '/api/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAccountTypeRoute = LoginAccountTypeRouteImport.update({
  id: '/$accountType',
  path: '/$accountType',
  getParentRoute: () => LoginRoute,
} as any)
const PartnerRegisterRoute = PartnerRegisterRouteImport.update({
  id: '/partner/register',
  path: '/partner/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffApplicationsRoute = StaffApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceRoute = StaffFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMessagesRoute = StaffMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPartnersRoute = StaffPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStudentsRoute = StaffStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTeamRoute = StaffTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StaffRoute,
} as any)
const StaffUniversitiesRoute = StaffUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVisasRoute = StaffVisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => StaffRoute,
} as any)
const ApiAuthAccountRoute = ApiAuthAccountRouteImport.update({
  id: '/api/auth/account',
  path: '/api/auth/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartnersRegisterRoute = ApiPartnersRegisterRouteImport.update({
  id: '/api/partners/register',
  path: '/api/partners/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffApplicationsIndexRoute = StaffApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffApplicationsRoute,
} as any)
const StaffApplicationsApplicationIdRoute =
  StaffApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => StaffApplicationsRoute,
  } as any)
const StaffPartnersPartnerCompanyIdRoute =
  StaffPartnersPartnerCompanyIdRouteImport.update({
    id: '/$partnerCompanyId',
    path: '/$partnerCompanyId',
    getParentRoute: () => StaffPartnersRoute,
  } as any)
const StaffStudentsStudentIdRoute = StaffStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StaffStudentsRoute,
} as any)
const StaffVisasIndexRoute = StaffVisasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffVisasRoute,
} as any)
const StaffVisasApplicationIdRoute = StaffVisasApplicationIdRouteImport.update({
  id: '/$applicationId',
  path: '/$applicationId',
  getParentRoute: () => StaffVisasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/503': typeof R503Route
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/staff': typeof StaffRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/support': typeof ApiSupportRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/login/$accountType': typeof LoginAccountTypeRoute
  '/partner/register': typeof PartnerRegisterRoute
  '/staff/applications': typeof StaffApplicationsRouteWithChildren
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/partners': typeof StaffPartnersRouteWithChildren
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/students': typeof StaffStudentsRouteWithChildren
  '/staff/team': typeof StaffTeamRoute
  '/staff/universities': typeof StaffUniversitiesRoute
  '/staff/visas': typeof StaffVisasRouteWithChildren
  '/staff/': typeof StaffIndexRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/partners/register': typeof ApiPartnersRegisterRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRoute
  '/staff/partners/$partnerCompanyId': typeof StaffPartnersPartnerCompanyIdRoute
  '/staff/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/staff/visas/$applicationId': typeof StaffVisasApplicationIdRoute
  '/staff/applications/': typeof StaffApplicationsIndexRoute
  '/staff/visas/': typeof StaffVisasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/503': typeof R503Route
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/support': typeof ApiSupportRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/login/$accountType': typeof LoginAccountTypeRoute
  '/partner/register': typeof PartnerRegisterRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/partners': typeof StaffPartnersRouteWithChildren
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/students': typeof StaffStudentsRouteWithChildren
  '/staff/team': typeof StaffTeamRoute
  '/staff/universities': typeof StaffUniversitiesRoute
  '/staff': typeof StaffIndexRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/partners/register': typeof ApiPartnersRegisterRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRoute
  '/staff/partners/$partnerCompanyId': typeof StaffPartnersPartnerCompanyIdRoute
  '/staff/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/staff/visas/$applicationId': typeof StaffVisasApplicationIdRoute
  '/staff/applications': typeof StaffApplicationsIndexRoute
  '/staff/visas': typeof StaffVisasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/503': typeof R503Route
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/staff': typeof StaffRouteWithChildren
  '/api/admin': typeof ApiAdminRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/support': typeof ApiSupportRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/login/$accountType': typeof LoginAccountTypeRoute
  '/partner/register': typeof PartnerRegisterRoute
  '/staff/applications': typeof StaffApplicationsRouteWithChildren
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/partners': typeof StaffPartnersRouteWithChildren
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/students': typeof StaffStudentsRouteWithChildren
  '/staff/team': typeof StaffTeamRoute
  '/staff/universities': typeof StaffUniversitiesRoute
  '/staff/visas': typeof StaffVisasRouteWithChildren
  '/staff/': typeof StaffIndexRoute
  '/api/auth/account': typeof ApiAuthAccountRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/partners/register': typeof ApiPartnersRegisterRoute
  '/staff/applications/$applicationId': typeof StaffApplicationsApplicationIdRoute
  '/staff/partners/$partnerCompanyId': typeof StaffPartnersPartnerCompanyIdRoute
  '/staff/students/$studentId': typeof StaffStudentsStudentIdRoute
  '/staff/visas/$applicationId': typeof StaffVisasApplicationIdRoute
  '/staff/applications/': typeof StaffApplicationsIndexRoute
  '/staff/visas/': typeof StaffVisasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/503'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/staff'
    | '/api/admin'
    | '/api/profile'
    | '/api/support'
    | '/api/workflow'
    | '/login/$accountType'
    | '/partner/register'
    | '/staff/applications'
    | '/staff/finance'
    | '/staff/messages'
    | '/staff/notifications'
    | '/staff/partners'
    | '/staff/settings'
    | '/staff/students'
    | '/staff/team'
    | '/staff/universities'
    | '/staff/visas'
    | '/staff/'
    | '/api/auth/account'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/partners/register'
    | '/staff/applications/$applicationId'
    | '/staff/partners/$partnerCompanyId'
    | '/staff/students/$studentId'
    | '/staff/visas/$applicationId'
    | '/staff/applications/'
    | '/staff/visas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/503'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/api/admin'
    | '/api/profile'
    | '/api/support'
    | '/api/workflow'
    | '/login/$accountType'
    | '/partner/register'
    | '/staff/finance'
    | '/staff/messages'
    | '/staff/notifications'
    | '/staff/partners'
    | '/staff/settings'
    | '/staff/students'
    | '/staff/team'
    | '/staff/universities'
    | '/staff'
    | '/api/auth/account'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/partners/register'
    | '/staff/applications/$applicationId'
    | '/staff/partners/$partnerCompanyId'
    | '/staff/students/$studentId'
    | '/staff/visas/$applicationId'
    | '/staff/applications'
    | '/staff/visas'
  id:
    | '__root__'
    | '/'
    | '/503'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/staff'
    | '/api/admin'
    | '/api/profile'
    | '/api/support'
    | '/api/workflow'
    | '/login/$accountType'
    | '/partner/register'
    | '/staff/applications'
    | '/staff/finance'
    | '/staff/messages'
    | '/staff/notifications'
    | '/staff/partners'
    | '/staff/settings'
    | '/staff/students'
    | '/staff/team'
    | '/staff/universities'
    | '/staff/visas'
    | '/staff/'
    | '/api/auth/account'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/partners/register'
    | '/staff/applications/$applicationId'
    | '/staff/partners/$partnerCompanyId'
    | '/staff/students/$studentId'
    | '/staff/visas/$applicationId'
    | '/staff/applications/'
    | '/staff/visas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R503Route: typeof R503Route
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  StaffRoute: typeof StaffRouteWithChildren
  ApiAdminRoute: typeof ApiAdminRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiSupportRoute: typeof ApiSupportRoute
  ApiWorkflowRoute: typeof ApiWorkflowRoute
  PartnerRegisterRoute: typeof PartnerRegisterRoute
  ApiAuthAccountRoute: typeof ApiAuthAccountRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiPartnersRegisterRoute: typeof ApiPartnersRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/503': {
      id: '/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof R503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support': {
      id: '/api/support'
      path: '/api/support'
      fullPath: '/api/support'
      preLoaderRoute: typeof ApiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow': {
      id: '/api/workflow'
      path: '/api/workflow'
      fullPath: '/api/workflow'
      preLoaderRoute: typeof ApiWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$accountType': {
      id: '/login/$accountType'
      path: '/$accountType'
      fullPath: '/login/$accountType'
      preLoaderRoute: typeof LoginAccountTypeRouteImport
      parentRoute: typeof LoginRoute
    }
    '/partner/register': {
      id: '/partner/register'
      path: '/partner/register'
      fullPath: '/partner/register'
      preLoaderRoute: typeof PartnerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/applications': {
      id: '/staff/applications'
      path: '/applications'
      fullPath: '/staff/applications'
      preLoaderRoute: typeof StaffApplicationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/finance': {
      id: '/staff/finance'
      path: '/finance'
      fullPath: '/staff/finance'
      preLoaderRoute: typeof StaffFinanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/messages': {
      id: '/staff/messages'
      path: '/messages'
      fullPath: '/staff/messages'
      preLoaderRoute: typeof StaffMessagesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/partners': {
      id: '/staff/partners'
      path: '/partners'
      fullPath: '/staff/partners'
      preLoaderRoute: typeof StaffPartnersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/students': {
      id: '/staff/students'
      path: '/students'
      fullPath: '/staff/students'
      preLoaderRoute: typeof StaffStudentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/team': {
      id: '/staff/team'
      path: '/team'
      fullPath: '/staff/team'
      preLoaderRoute: typeof StaffTeamRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/universities': {
      id: '/staff/universities'
      path: '/universities'
      fullPath: '/staff/universities'
      preLoaderRoute: typeof StaffUniversitiesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/visas': {
      id: '/staff/visas'
      path: '/visas'
      fullPath: '/staff/visas'
      preLoaderRoute: typeof StaffVisasRouteImport
      parentRoute: typeof StaffRoute
    }
    '/api/auth/account': {
      id: '/api/auth/account'
      path: '/api/auth/account'
      fullPath: '/api/auth/account'
      preLoaderRoute: typeof ApiAuthAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/partners/register': {
      id: '/api/partners/register'
      path: '/api/partners/register'
      fullPath: '/api/partners/register'
      preLoaderRoute: typeof ApiPartnersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/applications/': {
      id: '/staff/applications/'
      path: '/'
      fullPath: '/staff/applications/'
      preLoaderRoute: typeof StaffApplicationsIndexRouteImport
      parentRoute: typeof StaffApplicationsRoute
    }
    '/staff/applications/$applicationId': {
      id: '/staff/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/staff/applications/$applicationId'
      preLoaderRoute: typeof StaffApplicationsApplicationIdRouteImport
      parentRoute: typeof StaffApplicationsRoute
    }
    '/staff/partners/$partnerCompanyId': {
      id: '/staff/partners/$partnerCompanyId'
      path: '/$partnerCompanyId'
      fullPath: '/staff/partners/$partnerCompanyId'
      preLoaderRoute: typeof StaffPartnersPartnerCompanyIdRouteImport
      parentRoute: typeof StaffPartnersRoute
    }
    '/staff/students/$studentId': {
      id: '/staff/students/$studentId'
      path: '/$studentId'
      fullPath: '/staff/students/$studentId'
      preLoaderRoute: typeof StaffStudentsStudentIdRouteImport
      parentRoute: typeof StaffStudentsRoute
    }
    '/staff/visas/': {
      id: '/staff/visas/'
      path: '/'
      fullPath: '/staff/visas/'
      preLoaderRoute: typeof StaffVisasIndexRouteImport
      parentRoute: typeof StaffVisasRoute
    }
    '/staff/visas/$applicationId': {
      id: '/staff/visas/$applicationId'
      path: '/$applicationId'
      fullPath: '/staff/visas/$applicationId'
      preLoaderRoute: typeof StaffVisasApplicationIdRouteImport
      parentRoute: typeof StaffVisasRoute
    }
  }
}

interface LoginRouteChildren {
  LoginAccountTypeRoute: typeof LoginAccountTypeRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAccountTypeRoute: LoginAccountTypeRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface StaffApplicationsRouteChildren {
  StaffApplicationsApplicationIdRoute: typeof StaffApplicationsApplicationIdRoute
  StaffApplicationsIndexRoute: typeof StaffApplicationsIndexRoute
}

const StaffApplicationsRouteChildren: StaffApplicationsRouteChildren = {
  StaffApplicationsApplicationIdRoute: StaffApplicationsApplicationIdRoute,
  StaffApplicationsIndexRoute: StaffApplicationsIndexRoute,
}

const StaffApplicationsRouteWithChildren =
  StaffApplicationsRoute._addFileChildren(StaffApplicationsRouteChildren)

interface StaffPartnersRouteChildren {
  StaffPartnersPartnerCompanyIdRoute: typeof StaffPartnersPartnerCompanyIdRoute
}

const StaffPartnersRouteChildren: StaffPartnersRouteChildren = {
  StaffPartnersPartnerCompanyIdRoute: StaffPartnersPartnerCompanyIdRoute,
}

const StaffPartnersRouteWithChildren = StaffPartnersRoute._addFileChildren(
  StaffPartnersRouteChildren,
)

interface StaffStudentsRouteChildren {
  StaffStudentsStudentIdRoute: typeof StaffStudentsStudentIdRoute
}

const StaffStudentsRouteChildren: StaffStudentsRouteChildren = {
  StaffStudentsStudentIdRoute: StaffStudentsStudentIdRoute,
}

const StaffStudentsRouteWithChildren = StaffStudentsRoute._addFileChildren(
  StaffStudentsRouteChildren,
)

interface StaffVisasRouteChildren {
  StaffVisasApplicationIdRoute: typeof StaffVisasApplicationIdRoute
  StaffVisasIndexRoute: typeof StaffVisasIndexRoute
}

const StaffVisasRouteChildren: StaffVisasRouteChildren = {
  StaffVisasApplicationIdRoute: StaffVisasApplicationIdRoute,
  StaffVisasIndexRoute: StaffVisasIndexRoute,
}

const StaffVisasRouteWithChildren = StaffVisasRoute._addFileChildren(
  StaffVisasRouteChildren,
)

interface StaffRouteChildren {
  StaffApplicationsRoute: typeof StaffApplicationsRouteWithChildren
  StaffFinanceRoute: typeof StaffFinanceRoute
  StaffMessagesRoute: typeof StaffMessagesRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffPartnersRoute: typeof StaffPartnersRouteWithChildren
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffStudentsRoute: typeof StaffStudentsRouteWithChildren
  StaffTeamRoute: typeof StaffTeamRoute
  StaffUniversitiesRoute: typeof StaffUniversitiesRoute
  StaffVisasRoute: typeof StaffVisasRouteWithChildren
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffApplicationsRoute: StaffApplicationsRouteWithChildren,
  StaffFinanceRoute: StaffFinanceRoute,
  StaffMessagesRoute: StaffMessagesRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffPartnersRoute: StaffPartnersRouteWithChildren,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffStudentsRoute: StaffStudentsRouteWithChildren,
  StaffTeamRoute: StaffTeamRoute,
  StaffUniversitiesRoute: StaffUniversitiesRoute,
  StaffVisasRoute: StaffVisasRouteWithChildren,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R503Route: R503Route,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  StaffRoute: StaffRouteWithChildren,
  ApiAdminRoute: ApiAdminRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiSupportRoute: ApiSupportRoute,
  ApiWorkflowRoute: ApiWorkflowRoute,
  PartnerRegisterRoute: PartnerRegisterRoute,
  ApiAuthAccountRoute: ApiAuthAccountRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiPartnersRegisterRoute: ApiPartnersRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
